### ISSUE TITLE
termios bug on snow leopard

### ISSUE THREAD

**Issue by Sophrinix** [groner/pythinkgear#1]
great effort on the python library.

When I try to run this on snow leopard I get:

   $ python thinkgear.py

```
 Traceback (most recent call last):
 File "thinkgear.py", line 258, in <module>
   main()
 File "thinkgear.py", line 254, in main
   for pkt in ThinkGearProtocol('/dev/tty.MindSet-DevB-1').get_packets():
 File "thinkgear.py", line 69, in __init__
   self.serial = serial.Serial(port, 57600)
 File "/Library/Python/2.6/site-packages/serial/serialutil.py", line 192, in __init__
   self.open()
 File "/Library/Python/2.6/site-packages/serial/serialposix.py", line 288, in open
   self._reconfigurePort()
 File "/Library/Python/2.6/site-packages/serial/serialposix.py", line 417, in _reconfigurePort
   termios.tcsetattr(self.fd, TERMIOS.TCSANOW, [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])

  termios.error: (22, 'Invalid argument')
```

I hope this helps. BTW on Mac its /dev/tty.MindSet-DevB-1

**Comment by groner** [comment]
I will try to get my hands on a macbook next week and see if I can get this working.

A search of the Python issue tracker and the pyserial issue tracker didn't yield anything interesting.

**Comment by Sophrinix** [comment]
My suspicion is that this is a snow leopard problem.
The stock Ruby in snow leopard had a problem with termios.
The solution for Ruby was to rip rb-termios out and reload it from fresh source.

I take it from your message that pyserial is the python serial library.

I'll see what happens when I load that from an external source (or is it built into the python standard library?)

**Comment by Sophrinix** [comment]
to clarify the point on snow leopard.

I bet this would work on leopard.

Snow leopard's terminal.app program needlessly acts stupid.
A lot of stock development libraries in snow leopard are retarted.

They did a world of hurt on the stock ruby terminal stuff.
I bet python fared the same or worse.

**Comment by groner** [comment]
It looks like it's not part of the python standard library.  http://pyserial.sf.net/

You could try running 'stty </dev/tty.MindSet-DevB-1' to see if it can get/set tty bits.

If that works, a short term workaround might be to configure the device with a terminal, then replace the serial.Serial(...) call with open(...).

**Comment by Sophrinix** [comment]
I think I got this to work.

There sure is a lot of debug noise from this device.

I had to install pyserial from that link.
I also may have had to run a command that made all of python act in 32 bit mode.
I say may have because I am not sure if that step was material to making this work.

http://gist.github.com/217845

is that output normal?
